name: webview_flutter_plus
description: An extension of webview_flutter to load local HTML,CSS and Javascript from Assets or Strings and much more.
version: 0.1.1+10
homepage: https://github.com/shah-xad/webview_flutter_plus

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^1.0.3
  mime: ^0.9.7

dev_dependencies:
  flutter_test:
    sdk: flutter